AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Syncronize data from MSSQL to Parameter Store
Resources:
  SyncClientConfigToPS:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: Syncronize data from MSSQL to Parameter Store
      MemorySize: 128
      Timeout: 3
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AWSLambdaBasicExecutionRole
        - AmazonSSMFullAccess
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)
      VpcConfig:
        SecurityGroupIds:
          - VPC_SECURITY_GROUP
        SubnetIds:
          - VPC_SUBNET      
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:pyodbc:1"
